# Generated by Django 3.2.7 on 2021-09-22 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_alter_contact_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='email',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='phone',
        ),
        migrations.AddField(
            model_name='contact',
            name='status',
            field=models.CharField(choices=[('1', 'Phone'), ('2', 'Facebook'), ('3', 'Email')], default=1, max_length=100),
            preserve_default=False,
        ),
    ]
