# Generated by Django 3.2.7 on 2021-09-22 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0007_alter_course_branches'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category', to='course.category'),
        ),
        migrations.AlterField(
            model_name='course',
            name='contacts',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='course.contact'),
        ),
    ]
