# Generated by Django 3.2.7 on 2021-09-23 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0012_auto_20210923_1343'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branch',
            name='course',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='course',
        ),
        migrations.AddField(
            model_name='course',
            name='branches',
            field=models.ManyToManyField(null=True, related_name='branches', to='course.Branch'),
        ),
        migrations.AddField(
            model_name='course',
            name='contacts',
            field=models.ManyToManyField(null=True, related_name='contacts', to='course.Contact'),
        ),
    ]
