# Generated by Django 3.2.7 on 2021-10-24 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0013_auto_20210923_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='status',
            field=models.IntegerField(choices=[(1, 'Facebook'), (2, 'Email'), (3, 'phone')], default=1),
        ),
    ]
